### ISSUE TITLE
Validate Code - Gap in the login

### ISSUE THREAD

**Issue by gregw94542** [usspeedskating/tempus-public#12]
**Describe the bug**
Validation code complains when: In the situation where  skaters may skip "Semi B" since the number of skaters in the Final will be equal to the number fo skaters that would qualify for the final.

Donna's table entry: (note: no skaters in Semi B)

  | QUARTER A                      | SEMI A                                            | FINALS A-B | SEMI B                                    | FINALS C-F
#Sk | Rcs. | # Line   | Q        | #Sk | Rnk   | Rcs. | # Line | Q         | A | B             | #Sk | Rnk | Rcs. | # Line | Q | C | D | E | F
   14 | 4     | 2/4, 2/3 | 2+(2) | 10    | 1-10  | 2.     | 2/5      | 2+(1)   | 5 | 5             |        |         |         |             |     | 4 |    |    |  

[No Elimination - Short 5-6 on line]:5-6
SK. RCS  #LIne Q.    S RCS  #Line. Q. 
Q 	2+2	4,4,3,3	 S 	2+1	10/2	   S	4	4		F 5,5,4             # modified.  (add filler for B  Semi. 4 4 )
Q	2+2 4,4,3,3	 S	2+1  10/2	                                 F. 5,5,4		# Should be (leave

**Steps to Reproduce**
1. Open NoElimQT.txt
2. Add Race:   [Failing- Med 5-6 on line]:5-6
3. Add Line:     Q 	2+2	4,4,3,3	 S 	2+1	10/2	   S	4	4		F 5,5,4  
4. See error:    System Exception: "14 skaters for <race title> has 14 skaters in the "A" Quarterfinal, but subsequent rounds have 10 [skaters]
))

**Expected behavior**
Q	2+2 4,4,3,3	 S	2+1  10/2	                                 F 5,5,4		<-- should not generate error

**Comment by RobertBouillon** [comment]
Skaters that skip rounds can be denoted in the qualifiers field with a `-n`. 

The format is: `<Direct Qualifiers>[+<Extra Qualifiers>][-<Skaters Skipping Round>]`

Can you try this?

```
Q 2+2-4 4,4,3,3 S 2+1 10/2 S 4 4 F 5,5,4 
```

**Comment by gregw94542** [comment]
This permutation generated: 
Q 	2+2-4	4,4,3,3	S 	2+1	10/2	S	4	4		    F 5,5,4

System.Exception
  HResult=0x80131500
  Message='14' skaters for 'Bad - Short 5-6 on line' has 14 skaters in the 'A QuarterFinal', but the subsequent rounds have 14 skaters

==========================================================================
The version generated: 
Q 	2+2-4	4,4,3,3	S 	2+1	10/2			    F 5,5,4  
 
System.Exception
  HResult=0x80131500
  Message='14' skaters for 'No Elimination - Short 4-5 on line' has 14 skaters in the 'A QuarterFinal', but the subsequent rounds have 10 skaters

**Comment by RobertBouillon** [comment]
`Q 2+2-4 4,4,3,3 S 2+1 10/2 S 4 4 F 5,5,4` appears to be invalid because the Quarter defines 14 skaters, where 4 skip the next round. The next round (SemiFinal) has 14 skaters in two groups (it should only have 10 across both groups if 4 are skipping). If no skaters are skipping the next round, you can specify this and it will pass validation: `Q 2+2 4,4,3,3 S 2+1 10/2 S 4 4 F 5,5,4`. The error message isn't clear, so [I updated it](https://github.com/usspeedskating/tempus/commit/9b9d5b3ca3c2952ceadcc88786fa7a36b4606ce2).

`Q 2+2-4 4,4,3,3 S 2+1 10/2 F 5,5,4` Did not raise an error for me. If it still happens, can you post the entire text file?

**Comment by gregw94542** [comment]
Robear's clarification of this has resolved this issue. No code changes are required.. All changes were done on the Elimination Table File.
