### ISSUE TITLE
Importing Template file throws Unexpected Exception

### ISSUE THREAD

**Issue by gregw94542** [usspeedskating/tempus-public#17]
**Describe the bug**
Test Upload file throwing exception.   
I realize that you are probably under the gun with more serious bugs... If you can tell me what I need to change in my template, then I can continue with testing.

**Steps to Reproduce**
1. FileBrowser -> Import
2. Upload attached file 
[Greg Test Template.xlsx](https://github.com/usspeedskating/tempus-public/files/5875710/Greg.Test.Template.xlsx)

**Expected behavior**
Test file should upload or display display diagnostics

**Screenshots**
Qualification table NoElimination specified for Womensbb does not exist in
    the settings file at
  USS.Meets.Excel.DivisionDataSheet.ParseDivision(FinalsEventGroup finals, IEnumerable`1 data) at
  USS.Meets.Excel.DivisionDataSheet.Parse() at
  USS.Meets.Competition.Import(Workbook workbook, SheetTypes sheets) at
  USS.Meets.Competition.Import(Stream stream, SheetTypes sheets) at
  USS.Meets.Competition.LoadXml(Stream stream, SheetTypes sheets) at
  TempusBlazor.Client.Pages.FileBrowserPage.HandleFileSelected(InputFileChangeEventArgs args) at
  Microsoft.AspNetCore.Components.ComponentBase.CallSt
System.Exception: Qualification table NoElimination specified for Womensbb does not exist in
    the settings file at
  USS.Meets.Excel.DivisionDataSheet.ParseDivision(FinalsEventGroup finals, IEnumerable`1 data) at
  USS.Meets.Excel.DivisionDataSheet.Parse() at
  USS.Meets.Competition.Import(Workbook workbook, SheetTypes sheets) at
  USS.Meets.Competition.Import(Stream stream, SheetTypes sheets) at
  USS.Meets.Competition.LoadXml(Stream stream, SheetTypes sheets) at
  TempusBlazor.Client.Pages.FileBrowserPage.HandleFileSelected(InputFileChangeEventArgs args) at
  Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task

**Additional context**

**Comment by RobertBouillon** [comment]
The name of the qualification table you specified in the Excel sheet doesn't exist in the `NoElimQT.txt` file.

I'll update the documentation (#135) to make this more clear. You can find valid names for qualification tables in [this comment](https://github.com/usspeedskating/tempus-public/issues/15#issuecomment-881936196).
